---
- hosts: localhost
  tasks:
    - name: Creating VM
      os_server:
        auth:
          auth_url: "http://cpu06.codeurjc.es:5000/v2.0"
          password: Eil3rac8soojoam
          project_name: tub
          username: tub
        flavor: m1.tub
        auto_floating_ip: yes
        image: "Ubuntu Xenial"
        key_name: tub-ansible
        name: vm3
        state: present
        timeout: 200
        network: 9e909eed-34ca-424c-88f4-027385be7aa8
        security_groups:
          - SSH
          - Elastest
        meta:
          group: uge_master
          hostname: test1