apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edm-mysql-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        elastest-service: edm-mysql
    spec:
      containers:
      - name: edm-mysql
        image: elastest/edm-mysql:latest
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: elastest
        - name: MYSQL_PASSWORD
          value: elastest
        - name: MYSQL_USER
          value: elastest
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: edm-mysql
        - mountPath: /etc/mysql/conf.d
          name: edm-mysql-claim1
      restartPolicy: Always
      volumes:
      - name: edm-mysql
        persistentVolumeClaim:
          claimName: edm-mysql
      - name: edm-mysql-claim1
        persistentVolumeClaim:
          claimName: edm-mysql-claim1
status: {}
